name: Docker Image CI

on:
  push:
    branches: [ 12.0 ]
  pull_request:
    branches: [ 12.0 ]

jobs:

  build:

    runs-on: debian-buster-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./odoo/Dockerfile --tag my-image-name:$(date +%s)
